name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Production:
    name: Deploy to Google Compute Cloud
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.SSH_USER_NAME}}

        run: |
          echo "Deploying to Google Cloud"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          sudo ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }} '
          cd /home/rudranshshinghal91/v1 &&
          git reset --hard &&
          git checkout main &&
          git pull origin main &&
          sudo docker compose down &&
          sudo docker compose rm -fsv &&
          sudo docker compose up --build -d
          '
